import fs from 'fs';
import path from 'path';

const SRC_DIR = 'c:/art_web/antigravity/src';

const directories = [
  'components/portfolio',
  'components/aesthetics'
];

const files = [
  { path: 'components/portfolio/HeroSection.tsx', content: 'import React from "react";\nimport { Box, Typography } from "@mui/material";\nimport { Button } from "../ui/Button";\nimport { motion } from "framer-motion";\nimport Link from "next/link";\n\nexport default function HeroSection() {\n  return (\n    <Box sx={{ minHeight: "80vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", py: 8 }}>\n      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>\n        <Typography variant="h1" fontWeight={900} gutterBottom sx={{ letterSpacing: "-0.05em", fontSize: { xs: "4rem", md: "8rem" } }}>ARTY</Typography>\n        <Typography variant="h4" color="text.secondary" sx={{ mb: 6, fontWeight: 300 }}>Curated marketplace for aesthetics</Typography>\n        <Box sx={{ display: "flex", gap: 2, justifyContent: "center" }}>\n          <Button component={Link} href="/explore" variant="contained" size="large" sx={{ px: 4, py: 1.5 }}>Explore Creators</Button>\n          <Button component={Link} href="/login" variant="outlined" size="large" sx={{ px: 4, py: 1.5 }}>Login / Sign Up</Button>\n        </Box>\n      </motion.div>\n    </Box>\n  );\n}' },
  { path: 'components/portfolio/MottoSection.tsx', content: 'import React from "react";\nimport { Box, Typography, Container } from "@mui/material";\nimport { motion } from "framer-motion";\n\nexport default function MottoSection() {\n  return (\n    <Box sx={{ py: 12, bgcolor: "background.paper", textAlign: "center" }}>\n      <Container maxWidth="md">\n        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}>\n          <Typography variant="h3" fontWeight={700} gutterBottom sx={{ color: "primary.main" }}>People are the storefront.</Typography>\n          <Typography variant="h3" fontWeight={700} gutterBottom sx={{ color: "secondary.main" }}>Aesthetic is the category.</Typography>\n          <Typography variant="h3" fontWeight={700}>Items are the medium.</Typography>\n        </motion.div>\n      </Container>\n    </Box>\n  );\n}' },
  { path: 'components/portfolio/FeaturedCreators.tsx', content: 'import React from "react";\nimport { Box, Typography, Container, Grid2 } from "@mui/material";\nimport { UserCard } from "../users/UserCard";\n\n// Temporary mock data\nconst mockCreators = [\n  { username: "nischix", bio: "dark aesthetics & poetry", aesthetic: "noir", followers: 1200 },\n  { username: "luna", bio: "synthwave vibes", aesthetic: "vaporwave", followers: 850 },\n  { username: "mori", bio: "less is more", aesthetic: "minimal", followers: 2300 },\n];\n\nexport default function FeaturedCreators() {\n  return (\n    <Container sx={{ py: 8 }}>\n      <Typography variant="h4" fontWeight="bold" gutterBottom sx={{ mb: 4 }}>Featured Creators</Typography>\n      <Grid2 container spacing={4}>\n        {mockCreators.map((creator) => (\n          <Grid2 size={{ xs: 12, md: 4 }} key={creator.username}>\n             <UserCard username={creator.username} bio={creator.bio} />\n          </Grid2>\n        ))}\n      </Grid2>\n    </Container>\n  );\n}' },
  { path: 'components/portfolio/CreatorSpotlight.tsx', content: 'import React from "react";\nimport { Box, Typography, Container } from "@mui/material";\nexport default function CreatorSpotlight() { return <Container sx={{ py: 8 }}><Typography variant="h4">Creator Spotlight</Typography></Container>; }' },
  { path: 'components/portfolio/TrendingAesthetics.tsx', content: 'import React from "react";\nimport { Box, Typography, Container, Grid2, Paper } from "@mui/material";\n\nconst aesthetics = ["noir", "vaporwave", "grunge", "minimal", "cyberpunk", "brutalist"];\n\nexport default function TrendingAesthetics() {\n  return (\n    <Container sx={{ py: 8 }}>\n      <Typography variant="h4" fontWeight="bold" gutterBottom sx={{ mb: 4 }}>Trending Aesthetics</Typography>\n      <Grid2 container spacing={2}>\n        {aesthetics.map(a => (\n          <Grid2 size={{ xs: 6, sm: 4, md: 2 }} key={a}>\n             <Paper sx={{ p: 4, textAlign: "center", textTransform: "uppercase", fontWeight: "bold", bgcolor: "background.paper", "&:hover": { bgcolor: "action.hover" } }}>{a}</Paper>\n          </Grid2>\n        ))}\n      </Grid2>\n    </Container>\n  );\n}' },
  { path: 'components/portfolio/ExploreItems.tsx', content: 'import React from "react";\nimport { Box, Typography, Container } from "@mui/material";\nimport { ItemGrid } from "../items/ItemGrid";\n\nconst mockItems = [{ id: "1", title: "Black Hoodie", price: 120, imageUrl: "https://via.placeholder.com/200" }];\n\nexport default function ExploreItems() {\n  return (\n    <Box sx={{ py: 8, bgcolor: "background.paper" }}>\n      <Container>\n        <Typography variant="h4" fontWeight="bold" gutterBottom sx={{ mb: 4 }}>Trending Items</Typography>\n        <ItemGrid items={mockItems} />\n      </Container>\n    </Box>\n  );\n}' },
  { path: 'components/portfolio/CommunityPosts.tsx', content: 'import React from "react";\nimport { Typography, Container } from "@mui/material";\nexport default function CommunityPosts() { return <Container sx={{ py: 8 }}><Typography variant="h4">Community Posts</Typography></Container>; }' },
  { path: 'components/portfolio/CreatorStories.tsx', content: 'import React from "react";\nimport { Typography, Container, Box } from "@mui/material";\nimport { UserAvatar } from "../users/UserAvatar";\nexport default function CreatorStories() {\n  return (\n    <Container sx={{ py: 4, overflowX: "auto" }}>\n      <Box sx={{ display: "flex", gap: 3 }}>\n        {[1,2,3,4,5,6].map(i => <Box key={i} sx={{ textAlign: "center" }}><UserAvatar sx={{ width: 80, height: 80, border: "3px solid", borderColor: "primary.main" }} /><Typography variant="caption">nischix</Typography></Box>)}\n      </Box>\n    </Container>\n  );\n}' },
  { path: 'components/portfolio/AestheticShowcase.tsx', content: 'import React from "react";\nimport { Typography, Container } from "@mui/material";\nexport default function AestheticShowcase() { return <Container sx={{ py: 8 }}><Typography variant="h4">Aesthetic Showcase</Typography></Container>; }' },
  { path: 'components/portfolio/CreatorGrid.tsx', content: 'import React from "react";\nimport { Typography, Container } from "@mui/material";\nexport default function CreatorGrid() { return <Container sx={{ py: 8 }}><Typography variant="h4">Creator Grid</Typography></Container>; }' },
  { path: 'components/portfolio/MarketplacePreview.tsx', content: 'import React from "react";\nimport { Box, Typography, Container, Grid2 } from "@mui/material";\nexport default function MarketplacePreview() {\n  return (\n    <Box sx={{ py: 12, bgcolor: "background.paper" }}>\n      <Container>\n        <Typography variant="h3" textAlign="center" gutterBottom>Create. Share. Sell. Connect.</Typography>\n        <Grid2 container spacing={4} sx={{ mt: 6, textAlign: "center" }}>\n           {["Create your aesthetic storefront", "Share your culture", "Sell your curated items", "Connect with community"].map((text, i) => (\n             <Grid2 size={{ xs: 12, sm: 6, md: 3 }} key={i}><Typography variant="h6">{text}</Typography></Grid2>\n           ))}\n        </Grid2>\n      </Container>\n    </Box>\n  );\n}' },
  { path: 'components/portfolio/JoinCommunity.tsx', content: 'import React from "react";\nimport { Typography, Container } from "@mui/material";\nexport default function JoinCommunity() { return <Container sx={{ py: 8 }}><Typography variant="h4" textAlign="center">Join the Community</Typography></Container>; }' },
  { path: 'components/portfolio/StatsSection.tsx', content: 'import React from "react";\nimport { Container } from "@mui/material";\nimport { StorefrontStats } from "../storefront/StorefrontStats";\nexport default function StatsSection() {\n  return (\n    <Container sx={{ py: 8 }}>\n      <StorefrontStats stats={[{ label: "Creators", value: "1,200+" }, { label: "Items", value: "4,000+" }, { label: "Aesthetics", value: "15" }]} />\n    </Container>\n  );\n}' },
  { path: 'components/portfolio/Testimonials.tsx', content: 'import React from "react";\nimport { Typography, Container } from "@mui/material";\nexport default function Testimonials() { return <Container sx={{ py: 8 }}><Typography variant="h4" textAlign="center">Testimonials</Typography></Container>; }' },
  { path: 'components/portfolio/CTASection.tsx', content: 'import React from "react";\nimport { Box, Typography, Container } from "@mui/material";\nimport { Button } from "../ui/Button";\nexport default function CTASection() {\n  return (\n    <Box sx={{ py: 12, textAlign: "center" }}>\n      <Container>\n        <Typography variant="h3" fontWeight="bold" gutterBottom>Start your storefront</Typography>\n        <Typography variant="h6" color="text.secondary" sx={{ mb: 4 }}>Join the fastest growing aesthetic community.</Typography>\n        <Box sx={{ display: "flex", gap: 2, justifyContents: "center", justifyContent: "center" }}>\n          <Button variant="contained" size="large">Sign Up</Button>\n          <Button variant="outlined" size="large">Explore</Button>\n        </Box>\n      </Container>\n    </Box>\n  );\n}' },
  
  // Aesthetic Renderer
  { path: 'components/aesthetics/AestheticRenderer.tsx', content: 'import React from "react";\nimport { aestheticMap } from "../../aesthetics";\nimport { ThemeProvider } from "@mui/material/styles";\n\ninterface AestheticRendererProps {\n  aesthetic: keyof typeof aestheticMap;\n  children: React.ReactNode;\n}\n\nexport default function AestheticRenderer({ aesthetic, children }: AestheticRendererProps) {\n  const ThemeConfig = aestheticMap[aesthetic] || aestheticMap["noir"];\n  const ThemeComponent = ThemeConfig.ProfileLayout || (({ children }: any) => <>{children}</>);\n  \n  return (\n    <ThemeProvider theme={ThemeConfig.theme}>\n       <ThemeComponent>{children}</ThemeComponent>\n    </ThemeProvider>\n  );\n}' }
];

directories.forEach(dir => {
  const fullPath = path.join(SRC_DIR, dir);
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true });
    console.log(`Created directory: ${fullPath}`);
  }
});

files.forEach(file => {
  const fullPath = path.join(SRC_DIR, file.path);
  if (!fs.existsSync(fullPath)) {
    // Only unescape newlines if it wasn't done natively by json decode for node string literals.
    fs.writeFileSync(fullPath, file.content.replace(/\\\\n/g, '\\n'));
    console.log(`Created file: ${fullPath}`);
  }
});
